# uncompyle6 version 3.6.5
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.17 (default, Dec 23 2019, 21:25:33) 
# [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)]
# Embedded file name: /Users/versonator/Jenkins/live/output/Live/mac_64_static/Release/python-bundle/MIDI Remote Scripts/novation/sysex.py
# Compiled at: 2020-01-09 15:21:35
from __future__ import absolute_import, print_function, unicode_literals
SYSEX_START_BYTE = 240
SYSEX_END_BYTE = 247
NOVATION_MANUFACTURER_ID = (0, 32, 41)
DEVICE_FAMILY_MEMBER_CODE = (0, 0)
STD_MSG_HEADER = (
 SYSEX_START_BYTE,) + NOVATION_MANUFACTURER_ID + (2, )
LAYOUT_COMMAND_BYTE = 0
FADER_COMMAND_BYTE = 1
PRINT_COMMAND_BYTE = 3
NOTE_LAYOUT_COMMAND_BYTE = 15
FIRMWARE_MODE_COMMAND_BYTE = 16
SCALE_FEEDBACK_COMMAND_BYTE = 23
PRINT_ENABLE_COMMAND_BYTE = 24
STOP_FADER_COMMAND_BYTE = 25
STANDALONE_MODE_BYTE = 0
DAW_MODE_BYTE = 1
SESSION_LAYOUT_BYTE = 0
NOTE_LAYOUT_BYTE = 1
KEYS_LAYOUT_BYTE = 5
FADERS_LAYOUT_BYTE = 13
SCALE_LAYOUT_BYTE = 0
DRUM_LAYOUT_BYTE = 1
FADER_VERTICAL_ORIENTATION = 0
FADER_HORIZONTAL_ORIENTATION = 1
FADER_UNIPOLAR = 0
FADER_BIPOLAR = 1